#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
    set -x
    npm run prisma:generate
    rm -rf dist
    mkdir dist
    # cp -r src/* dist/
    # cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' > dist/tsconfig.json
    # cp -v tsconfig.build.json dist
    # cd dist
    # /usr/bin/find . -name '*.spec.ts' | xargs rm -rvf
    nest build
    # rm -rvf tsconfig.build.json tsconfig.json tsconfig.build.tsbuildinfo
    # cd ..
    mkdir -p dist/prisma/migrations
    cp -r prisma/migrations/* dist/prisma/migrations
    cp prisma/schema.prisma dist/prisma
    set +x
}

git_last_release_tag() {
    result=""
    rev=$(git rev-list --max-count=1 --tags="v[0-9]*\\.[0-9]*\\.[0-9]*")
    if [ -n "$rev" ]; then
        result=$(git describe --tags $rev)
    fi
    if [ -n "$result" ]; then
        result=$(git rev-list --max-parents=0 HEAD)
    fi
    echo $result
}

commit_lint() {
    set -x
    from=$(git_last_release_tag)
    commitlint --from $from
}

"$@"
